In [10]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [11]:
import numpy as np
print(np.__version__)

2.5.2


In [12]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print("Array created successfully:", arr)


Array created successfully: [1 2 3 4 5]


In [13]:
arr = np.linspace(1,10,20)
print(arr)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [ ]:
arr = np.zeros((2,3))
print(arr)


[[0. 0. 0.]
 [0. 0. 0.]]


array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
import numpy as np
arr = np.random.randn(2,3)
arr

array([[-0.10576458, -2.23886109,  1.55665944],
       [ 0.65474358, -1.92773964, -0.65619692]])

In [20]:
arr1 = np.ones((2,3))
print(arr1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [35]:
arr = np.random.arr = np.random.randint(1,30,6)
arr


array([ 9,  5, 18,  3,  6,  5], dtype=int32)